Added data model
amare1990/Blog-App pull request #1
Opened 2023-01-24 19:17 UTC by amare1990

- [ ] Added ror linter

2023-01-24 23:52 UTC, mirouhml requested changes
# REQUIRED CHANGES 🔴

Hi @amare1990, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media4.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif?cid=ecf05e47n6s5huda7qh40syoppcaspe9vx68ddmxerd08owm&rid=giphy.gif&ct=g)

## Highlights

- Great job setting up the correct linters ✔️
- Highly organized and clean code ✔️ 👨🏻‍💻
- Professional documentation ✔️
- Correct workflow ✔️
- Meaningful commit messages ✔️

## Required Changes ♻️
_Check the comments under the review._

- [ ] Please know that you should have a migration file for creating `comments` table, kindly add that.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-25 07:08 UTC, rloterh approved these changes
## Status: Approved :heavy_check_mark:

Hi Amare,  

Your project is complete! 🏁 There is nothing else to say other than... it's time to merge it 🍾 Congratulations!  🎉💯🌟 

## Highlights 👍
- Good job with migration query!

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

_Kindly consider my inline comments marked **[OPTIONAL]** under this review_

**You can also consider:**
- MIT license link in your ReadMe is broken, kindly endeavor to fix it.

Keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-25 07:08 UTC, rloterh commented on db/migrate/20230124221753_create_posts.rb
> +    add_index :posts, :authorid
- [ ] OPTIONAL
Taking into consideration the given ERD, we can see that `user` model is referenced using foreign key in models as `AuthorId`. Let's therefore bear in mind that `author` is aliasing the `user` model, and hence, our migration query should be similar to:

```ruby
...
  def change
    add_reference :posts, :author, references: :users, null: false, foreign_key: {to_table: :users}
  end
...

```

or.. 

```ruby
  create_table :posts do |t|
    . . .
    t.references :author, foreign_key: { to_table: 'users' } 
    . . .
  end
```

2023-01-25 07:08 UTC, rloterh commented on db/migrate/20230124222320_create_likes.rb
> +    add_index :likes, :authorid
- [ ]OPTIONAL
 Similarly, the `user` model is referenced using foreign key in models as `AuthorId`, and `author` an alias of `user` hence, our migration query should be similar to:

```ruby
...
  def change
    add_reference :likes, :author, references: :users, null: false, foreign_key: {to_table: :users}
  end
...

```

or.. 

```ruby
  create_table :likes do |t|
    . . .
    t.references :author, foreign_key: { to_table: 'users' } 
    . . .
  end
```

2023-01-25 07:08 UTC, rloterh commented on db/migrate/20230125060440_create_comments.rb
> +    add_index :comments, :authorid
- [ ] Again, the `user` model is referenced using foreign key in models as `AuthorId`, and `author` an alias of `user` hence, our migration query should be similar to:

```ruby
...
  def change
    add_reference :comments, :author, references: :users, null: false, foreign_key: {to_table: :users}
  end
...

```

or.. 

```ruby
  create_table :comments do |t|
    . . .
    t.references :author, foreign_key: { to_table: 'users' } 
    . . .
  end
```

2023-01-25 07:30 UTC, merged